### ISSUE TITLE
Why not use latest rkbin?

### ISSUE THREAD

**Issue by paschun** [inindev/uboot-rockchip#1]
https://github.com/rockchip-linux/rkbin/blob/master/bin/rk35/rk3568_bl31_v1.43.elf
https://github.com/rockchip-linux/rkbin/blob/master/bin/rk35/rk3568_ddr_1560MHz_v1.18.bin

Thanks for your images btw 😎

**Comment by inindev** [comment]
I keep thinking the official ATF will arrive but maybe you are right and I should test to see if I can find a more recent working pair.

rk3568: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/16952
rk3588: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/21840

**Comment by paschun** [comment]
I don't know much about this stuff but seems to boot fine on odroid-m1
```
DDR V1.18 f366f69a7d typ 23/07/17-15:48:58
NOTICE:  BL31: v2.3():v2.3-607-gbf602aff1:cl
NOTICE:  BL31: Built : 10:16:03, Jun  5 2023
```

**Comment by Goetterfunke87** [comment]
Hi inindev, Thank you for your nice repos again! 👍  You may have a look at my post at radxa-forum: https://forum.radxa.com/t/radxa-rock-5b-hangs-multiple-times-a-week/20214/17 I had to use more recent rkbins from rockchip to get your image working stable on 32 gb rock 5b. After testing for a while now I can definately say they are more stable than the old ones. Best Regards

**Comment by inindev** [comment]
> Hi inindev, Thank you for your nice repos again! 👍 You may have a look at my post at radxa-forum: https://forum.radxa.com/t/radxa-rock-5b-hangs-multiple-times-a-week/20214/17 I had to use more recent rkbins from rockchip to get your image working stable on 32 gb rock 5b. After testing for a while now I can definately say they are more stable than the old ones. Best Regards

Thank you for tracking this down. I am going to try and run a rebuild of this repo updating to the latest sources and binaries.

What versions of the binaries did you have success with?
https://github.com/rockchip-linux/rkbin/tree/master/bin/rk35

**Comment by Goetterfunke87** [comment]
Hi There, yes, these are the same bins I'm currently using with your 6.7 image on my server and with Ubuntu from Joshua Riek on my self made "laptop". On my server I rendered OSM maps for more than 20 days with 100 % ram usage (32 gb + 64 gb nvme swap) and zero errors / freezes / crashes. Funfact: the only image I currently can use my PS5 controller native on is my server with your image. Since it includes hid_playstation kernelmodule still missing in the older kernel versions :D

**Comment by paschun** [comment]
It appears 3568 support was finally merged.

> I keep thinking the official ATF will arrive but maybe you are right and I should test to see if I can find a more recent working pair.
> 
> rk3568: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/16952 rk3588: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/21840

**Comment by inindev** [comment]
I am expecting it to land in the next few weeks.  In the mean time, I did what you suggested and just grab the latest-and-greatest each build: https://github.com/inindev/uboot-rockchip/blob/main/Makefile#L97-L111

2024.07 will GA tomorrow and I will have that build up

**Comment by inindev** [comment]
builds now always use the latest rock bins:
https://github.com/inindev/uboot-rockchip/blob/main/Makefile#L97-L111

**Comment by paschun** [comment]
ty for sharing your excellent work on this :)
